//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaRosse_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vestuario
    {
        public string Id { get; set; }
        public string Nombre_prenda { get; set; }
        public string Talla { get; set; }
        public string Color { get; set; }
        public string Precio { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
